services:
  - type: web
    name: f1-predictor
    env: python
    plan: free
    buildCommand: "pip install -r requirement.txt"
    startCommand: "py -m uvicorn main:app --host 127.0.0.1 --port 8000"
    healthCheckPath: /health
    autoDeploy: true
